# Utility functions

## z-score util function

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# read the data
nls97 = pd.read_csv("../05-data_cleaning/data/nls97.csv").dropna()

nls97

,personid,gender,birthmonth,birthyear,highestgradecompleted,maritalstatus,childathome,childnotathome,wageincome,weeklyhrscomputer,...,colenrfeb13,colenroct13,colenrfeb14,colenroct14,colenrfeb15,colenroct15,colenrfeb16,colenroct16,colenrfeb17,colenroct17
783,177272,Male,6,1981,14.0,Married,2.0,0.0,48000.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
3297,427651,Female,7,1983,13.0,Never-married,1.0,0.0,33000.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
3651,462520,Female,10,1981,18.0,Married,1.0,0.0,73000.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
3831,481711,Female,2,1984,19.0,Never-married,2.0,0.0,31139.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
4253,526446,Male,11,1980,20.0,Married,3.0,0.0,128000.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
5221,623704,Male,12,1984,19.0,Never-married,2.0,0.0,30000.0,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
6062,709844,Female,12,1980,17.0,Married,2.0,0.0,5000.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
6729,777472,Female,9,1981,18.0,Married,2.0,0.0,71000.0,10 hours or more a week,...,4. Graduate program,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,4. Graduate program,4. Graduate program,4. Graduate program,4. Graduate program,4. Graduate program
6797,782720,Male,3,1980,16.0,Married,1.0,0.0,70000.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
7873,888158,Female,8,1982,18.0,Married,2.0,0.0,100000.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
8195,917825,Male,7,1984,14.0,Married,1.0,1.0,50000.0,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled

If we are tasked to compute the z-scores of `wageincome`, `satverbal`, `satmath`, `gpaoverall`, `gpaenglish`, `gpamath`, `gpascience`, at the same time, all the z-scores for those variables based on their `maritalstatus`, we need to compute many many times.

For example:

In [5]:
nls97['wageincome_z_score'] = (nls97['wageincome'] - nls97['wageincome'].mean())/nls97['wageincome'].std()
nls97['satverbal_z_score'] = (nls97['satverbal'] - nls97['satverbal'].mean())/nls97['satverbal'].std()
nls97['satmath_z_score'] = (nls97['satmath'] - nls97['satmath'].mean())/nls97['satmath'].std()
nls97['gpaoverall_z_score'] = (nls97['gpaoverall'] - nls97['gpaoverall'].mean())/nls97['gpaoverall'].std()
nls97['gpaenglish_z_score'] = (nls97['gpaenglish'] - nls97['gpaenglish'].mean())/nls97['wageincome'].std()
nls97['gpascience_z_score'] = (nls97['gpascience'] - nls97['gpascience'].mean())/nls97['gpascience'].std()

nls97[[i for i in nls97.columns if 'z_score' in i]].head(10)

,wageincome_z_score,satverbal_z_score,satmath_z_score,gpaoverall_z_score,gpaenglish_z_score,gpascience_z_score
783,-0.288022,-1.121206,-0.639242,0.216853,0.000487,-1.088741
3297,-0.715628,-0.563140,-0.897284,0.302046,0.000544,-1.036367
3651,0.424654,0.999446,0.909014,0.955188,-0.000311,0.971297
3831,-0.768680,-0.674753,-0.768263,-0.464686,-0.000368,-0.338049
4253,1.992541,1.557513,1.683141,0.841598,0.001057,1.669615
5221,-0.801149,-1.232820,-0.897284,-1.231417,-0.001366,-0.460255
6062,-1.513825,0.162347,-0.639242,-1.373405,-0.001166,-1.123657
6729,0.367640,1.334286,1.554120,1.693522,0.001970,1.110961
6797,0.339133,-0.563140,0.070375,-0.237506,0.000060,0.150773
7873,1.194344,0.720413,0.457439,0.500828,0.000544,0.831633

The above cell is not only very long, every time you need to compute a new z_score, you need to write it again. Alternative way is to write a function.

In [6]:
def z_score(series:pd.Series)->pd.Series:
    return (series - series.mean()) / series.std()

for col in ['wageincome', 'satverbal', 'satmath', 'gpaoverall', 'gpaenglish', 'gpamath', 'gpascience']:
    nls97[f"{col}_z_score"] = z_score(nls97[col])

nls97[[i for i in nls97.columns if 'z_score' in i]]

,wageincome_z_score,satverbal_z_score,satmath_z_score,gpaoverall_z_score,gpaenglish_z_score,gpascience_z_score,gpamath_z_score
783,-0.288022,-1.121206,-0.639242,0.216853,0.456433,-1.088741,-1.019768
3297,-0.715628,-0.563140,-0.897284,0.302046,0.509845,-1.036367,0.446565
3651,0.424654,0.999446,0.909014,0.955188,-0.291340,0.971297,0.299932
3831,-0.768680,-0.674753,-0.768263,-0.464686,-0.344753,-0.338049,-0.433235
4253,1.992541,1.557513,1.683141,0.841598,0.990557,1.669615,1.297039
5221,-0.801149,-1.232820,-0.897284,-1.231417,-1.279469,-0.460255,-1.576975
6062,-1.513825,0.162347,-0.639242,-1.373405,-1.092526,-1.123657,-1.210392
6729,0.367640,1.334286,1.554120,1.693522,1.845155,1.110961,1.179732
6797,0.339133,-0.563140,0.070375,-0.237506,0.055840,0.150773,0.079982
7873,1.194344,0.720413,0.457439,0.500828,0.509845,0.831633,1.179732
8195,-0.231008,-0.618947,-0.832774,-1.203020,-1.359588,-0.687208,-0.242612

You can call it in groupby as well

In [7]:
for col in ['wageincome', 'satverbal', 'satmath', 'gpaoverall', 'gpaenglish', 'gpamath', 'gpascience']:
    nls97[f"{col}_z_score_by_marital_status"] = nls97.groupby("maritalstatus")[col].transform(z_score)

nls97[[i for i in nls97.columns if 'z_score_by' in i]]

,wageincome_z_score_by_marital_status,satverbal_z_score_by_marital_status,satmath_z_score_by_marital_status,gpaoverall_z_score_by_marital_status,gpaenglish_z_score_by_marital_status,gpamath_z_score_by_marital_status,gpascience_z_score_by_marital_status
783,-0.550511,-1.435730,-0.961071,0.040012,0.299877,-1.231119,-1.219374
3297,1.069943,0.725866,-0.577350,1.000000,0.984746,0.953821,-1.139096
3651,0.133354,0.693352,0.589565,0.733548,-0.407202,0.105843,0.686403
3831,-0.158918,0.414781,1.154701,0.000000,0.029841,0.086711,0.733391
4253,1.637855,1.253637,1.364883,0.626850,0.804933,1.115992,1.332429
5221,-0.911025,-1.140647,-0.577350,-1.000000,-1.014586,-1.040532,0.405706
6062,-1.726758,-0.147075,-0.961071,-1.453758,-1.164786,-1.424236,-1.251676
6729,0.078644,1.029523,1.235663,1.427084,1.613023,0.997151,0.815608
6797,0.051290,-0.875445,-0.250363,-0.386780,-0.078915,-0.116984,-0.072678
7873,0.871927,0.413210,0.137296,0.306756,0.350383,0.997151,0.557198
8195,-0.495802,-0.931473,-1.154901,-1.293711,-1.417314,-0.443797,-0.847909

# Method Chaining

_Method chaining_ is a coding style where multiple DataFrame or Series operations are invoked sequentially using the dot (.) operator, creating a single, fluid data transformation pipeline. This approach improves readability and maintainability by eliminating the need for intermediate variables and presenting the data flow as a clear sequence of steps.

## Example: Comparing code with and without method chaining

goal: Analyze survival rate and average fare per person by family size.
We will first create two new columns:

- family_size
- fare_per_person

Then compute summary statistics.

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Traditional (Non-Chained) Approach:

In [12]:
# Step 1: create family size
df["family_size"] = df["SibSp"] + df["Parch"] + 1

# Step 2: create fare per person
df["fare_per_person"] = df["Fare"] / df["family_size"]

# Step 3: group and aggregate
result = df.groupby("family_size").agg(
    survival_rate = ("Survived", "mean"),
    avg_fare_per_person = ("fare_per_person", "mean"),
    passenger_count = ("PassengerId", "count")
)

# Step 4: sort results
result = result.sort_index()

result

             survival_rate  avg_fare_per_person  passenger_count
family_size
1                 0.303538            21.242689              537
2                 0.552795            24.947064              161
3                 0.578431            13.230827              102
4                 0.724138            13.716128               29
5                 0.200000            11.618891               15
6                 0.136364            12.287121               22
7                 0.333333             4.195238               12
8                 0.000000             5.862500                6
11                0.000000             6.322727                7

Issues with this approach
- many intermediate mutations
- dataframe gets modified multiple times
- harder to track workflow in longer pipelines

### Method chaining version:

In [13]:
result = (
    df
    .assign(
        family_size = lambda x: x["SibSp"] + x["Parch"] + 1,
        fare_per_person = lambda x: x["Fare"] / x["family_size"]
    )
    .groupby("family_size")
    .agg(
        survival_rate = ("Survived", "mean"),
        avg_fare_per_person = ("fare_per_person", "mean"),
        passenger_count = ("PassengerId", "count")
    )
    .sort_index()
)

result

             survival_rate  avg_fare_per_person  passenger_count
family_size
1                 0.303538            21.242689              537
2                 0.552795            24.947064              161
3                 0.578431            13.230827              102
4                 0.724138            13.716128               29
5                 0.200000            11.618891               15
6                 0.136364            12.287121               22
7                 0.333333             4.195238               12
8                 0.000000             5.862500                6
11                0.000000             6.322727                7

# Data operation pipeline using `df.pipe()`
We will be using the example from [Demo 0611](https://github.com/jieshu-wang-SBU/EST389_371_2026_spring/blob/main/lectures/06-Exploratory_data_analysis/06-11_Example_transform_and_EDA_census_dataset.ipynb), and let's write a pipeline that does the same things in Demo 0611.

In [30]:
import matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ny_age = pd.read_csv("../06-Exploratory_data_analysis/data/ACSST5Y2023.S0101-2026-02-23T201031.csv")

ny_age.head()

,Label (Grouping),"Albany County, New York!!Total!!Estimate","Albany County, New York!!Percent!!Estimate","Albany County, New York!!Male!!Estimate","Albany County, New York!!Percent Male!!Estimate","Albany County, New York!!Female!!Estimate","Albany County, New York!!Percent Female!!Estimate","Allegany County, New York!!Total!!Estimate","Allegany County, New York!!Percent!!Estimate","Allegany County, New York!!Male!!Estimate",...,"Wyoming County, New York!!Male!!Estimate","Wyoming County, New York!!Percent Male!!Estimate","Wyoming County, New York!!Female!!Estimate","Wyoming County, New York!!Percent Female!!Estimate","Yates County, New York!!Total!!Estimate","Yates County, New York!!Percent!!Estimate","Yates County, New York!!Male!!Estimate","Yates County, New York!!Percent Male!!Estimate","Yates County, New York!!Female!!Estimate","Yates County, New York!!Percent Female!!Estimate"
0,Total population,"315,374",(X),"153,188",(X),"162,186",(X),"47,027",(X),"23,865",...,"21,429",(X),"18,551",(X),"24,637",(X),"12,084",(X),"12,553",(X)
1,AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Under 5 years,"14,928",4.7%,"7,577",4.9%,"7,351",4.5%,"2,396",5.1%,"1,187",...,905,4.2%,985,5.3%,"1,557",6.3%,839,6.9%,718,5.7%
3,5 to 9 years,"15,626",5.0%,"8,058",5.3%,"7,568",4.7%,"2,425",5.2%,"1,369",...,"1,068",5.0%,"1,039",5.6%,"1,506",6.1%,760,6.3%,746,5.9%
4,10 to 14 years,"16,773",5.3%,"8,581",5.6%,"8,192",5.1%,"2,803",6.0%,"1,323",...,"1,002",4.7%,"1,083",5.8%,"1,657",6.7%,767,6.3%,890,7.1%

You can even use for loop to make the code even smaller

In [73]:
def strip_white_spaces(df:pd.DataFrame)->pd.DataFrame:
    for col in df.columns:
        if df[col].dtype == object:
            df[col] = df[col].str.strip()
    return df

def select_non_stat_cols(df:pd.DataFrame, stat_cols:tuple=("Percent",'Total'))->pd.DataFrame:
    cols = df.columns.tolist()
    keep_cols = []
    for col in cols:
        keep = True
        for stat_col in stat_cols:
            if stat_col in col:
                keep = False
                break
        if keep:
            keep_cols.append(col)
    return df[keep_cols].copy()

def select_population_groups(df:pd.DataFrame,
                             label:str="Label (Grouping)",
                             groups:tuple=("Total population", "Under 18 years", "65 years and over"))->pd.DataFrame:
    return df[df[label].isin(list(groups))].copy()

def reset_columns_names(df:pd.DataFrame)->pd.DataFrame:
    df.columns = df.iloc[0]
    df = df.iloc[1:].copy()
    return df

def cast_to_numeric(df:pd.DataFrame)->pd.DataFrame:
    for col in df.columns[1:]:
        df[col] = df[col].str.replace(",", "")
        df[col] = pd.to_numeric(df[col], errors="coerce")
    return df

def extract_county_name(string: str) -> str:
    return string.split(",")[0]

result = (ny_age
          .pipe(strip_white_spaces)
          .pipe(select_non_stat_cols)
          .pipe(select_population_groups, groups=("Total population", "Under 18 years", "65 years and over"))
          .T.reset_index()
          .pipe(reset_columns_names)
          .pipe(cast_to_numeric).rename(columns={'Label (Grouping)': 'county',
                                                 'Under 18 years': 'child',
                                                 '65 years and over': 'senior'})
          .assign(adult=lambda x: x['Total population'] - x['child'] - x['senior'])
          .drop(columns=['Total population'])
          .assign(gender=lambda x: "M" if "Male" in x['county'] else "F")
          .assign(county=lambda x: x['county'].apply(extract_county_name)))[['county', 'gender', 'child', 'adult','senior']]

result

0                county gender   child   adult  senior
1         Albany County      F   29296   99324   24568
2         Albany County      F   28137  102485   31564
3       Allegany County      F    4803   14536    4526
4       Allegany County      F    4541   13868    4753
5          Bronx County      F  177091  414274   79363
..                  ...    ...     ...     ...     ...
120  Westchester County      F  104119  306495  100289
121      Wyoming County      F    3667   13857    3905
122      Wyoming County      F    3810   10710    4031
123        Yates County      F    2810    6658    2616
124        Yates County      F    2816    6961    2776

[124 rows x 5 columns]

In [77]:
from functools import partial, reduce

pipeline = [strip_white_spaces,
            select_non_stat_cols,
            partial(select_population_groups, groups=("Total population", "Under 18 years", "65 years and over")),
            lambda df: df.T.reset_index(),
            reset_columns_names,
            cast_to_numeric,
            lambda df: df.rename(columns={'Label (Grouping)': 'county','Under 18 years': 'child','65 years and over': 'senior'}),
            lambda df: df.assign(adult=lambda x: x['Total population'] - x['child'] - x['senior']),
            lambda df: df.drop(columns=['Total population']),
            lambda df: df.assign(gender=lambda x: "M" if "Male" in x['county'] else "F"),
            lambda df: df.assign(county=lambda x: x['county'].apply(extract_county_name)),
            lambda df: df[['county', 'gender', 'child', 'adult','senior']]
            ]

result = reduce(lambda v, f: f(v), pipeline, ny_age)
result

0                county gender   child   adult  senior
1         Albany County      F   29296   99324   24568
2         Albany County      F   28137  102485   31564
3       Allegany County      F    4803   14536    4526
4       Allegany County      F    4541   13868    4753
5          Bronx County      F  177091  414274   79363
..                  ...    ...     ...     ...     ...
120  Westchester County      F  104119  306495  100289
121      Wyoming County      F    3667   13857    3905
122      Wyoming County      F    3810   10710    4031
123        Yates County      F    2810    6658    2616
124        Yates County      F    2816    6961    2776

[124 rows x 5 columns]