# Utility functions

## z-score util function

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# read the data
nls97 = pd.read_csv("../05-data_cleaning/data/nls97.csv")

nls97

,personid,gender,birthmonth,birthyear,highestgradecompleted,maritalstatus,childathome,childnotathome,wageincome,weeklyhrscomputer,...,colenrfeb13,colenroct13,colenrfeb14,colenroct14,colenrfeb15,colenroct15,colenrfeb16,colenroct16,colenrfeb17,colenroct17
0,100061,Female,5,1980,13.0,Married,4.0,0.0,12500.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
1,100139,Male,9,1983,12.0,Married,2.0,0.0,120000.0,1 to 3 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
2,100284,Male,11,1984,7.0,Never-married,1.0,0.0,58000.0,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
3,100292,Male,4,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,NaN,NaN,NaN,NaN
4,100583,Male,1,1980,13.0,Married,4.0,0.0,30000.0,Less than 1 hour a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8979,999291,Female,4,1981,16.0,Married,NaN,NaN,35000.0,7 to 9 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
8980,999406,Male,7,1982,14.0,Never-married,NaN,NaN,116000.0,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
8981,999543,Female,8,1984,12.0,Divorced,2.0,0.0,NaN,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
8982,999698,Female,5,1983,12.0,Never-married,5.0,0.0,NaN,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
8983,999963,Female,9,1982,17.0,Married,2.0,0.0,50000.0,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled

If we are tasked to compute the z-scores of `wageincome`, `satverbal`, `satmath`, `gpaoverall`, `gpaenglish`, `gpamath`, `gpascience`, at the same time, all the z-scores for those variables based on their `maritalstatus`, we need to compute many many times.

For example:

In [5]:
nls97['wageincome_z_score'] = (nls97['wageincome'] - nls97['wageincome'].mean())/nls97['wageincome'].std()
nls97['satverbal_z_score'] = (nls97['satverbal'] - nls97['satverbal'].mean())/nls97['satverbal'].std()
nls97['satmath_z_score'] = (nls97['satmath'] - nls97['satmath'].mean())/nls97['satmath'].std()
nls97['gpaoverall_z_score'] = (nls97['gpaoverall'] - nls97['gpaoverall'].mean())/nls97['gpaoverall'].std()
nls97['gpaenglish_z_score'] = (nls97['gpaenglish'] - nls97['gpaenglish'].mean())/nls97['wageincome'].std()
nls97['gpascience_z_score'] = (nls97['gpascience'] - nls97['gpascience'].mean())/nls97['gpascience'].std()

The above cell is not only very long, every time you need to compute a new z_score, you need to write it again. Alternative way is to write a function.

In [6]:
def z_score(series:pd.Series)->pd.Series:
    return (series - series.mean()) / series.std()

for col in ['wageincome', 'satverbal', 'satmath', 'gpaoverall', 'gpaenglish', 'gpamath', 'gpascience']:
    nls97[f"{col}_z_score"] = z_score(nls97[col])

nls97[[i for i in nls97.columns if 'z_score' in i]]

,wageincome_z_score,satverbal_z_score,satmath_z_score,gpaoverall_z_score,gpaenglish_z_score,gpascience_z_score,gpamath_z_score
0,-0.909024,NaN,NaN,0.391968,1.044678,0.649875,0.260370
1,1.733701,NaN,NaN,NaN,NaN,NaN,NaN
2,0.209525,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,1.024719,0.977167,0.457137,1.465971
4,-0.478813,NaN,NaN,0.148603,0.140033,-0.313815,0.327348
...,...,...,...,...,...,...,...
8979,-0.355896,-0.532460,-1.310016,0.473090,0.680120,0.521383,0.260370
8980,1.635367,-0.354153,-0.527089,-1.052001,0.099527,-1.560189,-1.963293
8981,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8982,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8983,0.012857,-0.354153,1.386732,1.560123,1.476747,0.881161,1.104291

You can call it in groupby as well

In [10]:
for col in ['wageincome', 'satverbal', 'satmath', 'gpaoverall', 'gpaenglish', 'gpamath', 'gpascience']:
    nls97[f"{col}_z_score_by_marital_status"] = nls97.groupby("maritalstatus")[col].transform(z_score)

nls97[[i for i in nls97.columns if 'z_score_by' in i]]

,wageincome_z_score_by_marital_status,satverbal_z_score_by_marital_status,satmath_z_score_by_marital_status,gpaoverall_z_score_by_marital_status,gpaenglish_z_score_by_marital_status,gpamath_z_score_by_marital_status,gpascience_z_score_by_marital_status
0,-0.983652,NaN,NaN,0.181975,0.886116,0.117153,0.506129
1,1.344725,NaN,NaN,NaN,NaN,NaN,NaN
2,0.513944,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.604614,NaN,NaN,-0.075845,-0.044312,0.187386,-0.502495
...,...,...,...,...,...,...,...
8979,-0.496317,-0.608881,-1.392514,0.267915,0.511168,0.117153,0.371646
8980,2.299780,-0.303012,-0.434335,-0.916382,0.220543,-1.837881,-1.506938
8981,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8982,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8983,-0.171427,-0.423504,1.275783,1.419512,1.330500,1.002090,0.748199

# Method Chaining

_Method chaining_ is a coding style where multiple DataFrame or Series operations are invoked sequentially using the dot (.) operator, creating a single, fluid data transformation pipeline. This approach improves readability and maintainability by eliminating the need for intermediate variables and presenting the data flow as a clear sequence of steps.

## Example: Comparing code with and without method chaining

goal: Analyze survival rate and average fare per person by family size.
We will first create two new columns:

- family_size
- fare_per_person

Then compute summary statistics.

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Traditional (Non-Chained) Approach:

In [12]:
# Step 1: create family size
df["family_size"] = df["SibSp"] + df["Parch"] + 1

# Step 2: create fare per person
df["fare_per_person"] = df["Fare"] / df["family_size"]

# Step 3: group and aggregate
result = df.groupby("family_size").agg(
    survival_rate = ("Survived", "mean"),
    avg_fare_per_person = ("fare_per_person", "mean"),
    passenger_count = ("PassengerId", "count")
)

# Step 4: sort results
result = result.sort_index()

result

             survival_rate  avg_fare_per_person  passenger_count
family_size
1                 0.303538            21.242689              537
2                 0.552795            24.947064              161
3                 0.578431            13.230827              102
4                 0.724138            13.716128               29
5                 0.200000            11.618891               15
6                 0.136364            12.287121               22
7                 0.333333             4.195238               12
8                 0.000000             5.862500                6
11                0.000000             6.322727                7

Issues with this approach
- many intermediate mutations
- dataframe gets modified multiple times
- harder to track workflow in longer pipelines

### Method chaining version:

In [13]:
result = (
    df
    .assign(
        family_size = lambda x: x["SibSp"] + x["Parch"] + 1,
        fare_per_person = lambda x: x["Fare"] / x["family_size"]
    )
    .groupby("family_size")
    .agg(
        survival_rate = ("Survived", "mean"),
        avg_fare_per_person = ("fare_per_person", "mean"),
        passenger_count = ("PassengerId", "count")
    )
    .sort_index()
)

result

             survival_rate  avg_fare_per_person  passenger_count
family_size
1                 0.303538            21.242689              537
2                 0.552795            24.947064              161
3                 0.578431            13.230827              102
4                 0.724138            13.716128               29
5                 0.200000            11.618891               15
6                 0.136364            12.287121               22
7                 0.333333             4.195238               12
8                 0.000000             5.862500                6
11                0.000000             6.322727                7