# Spatial join
Example: assign neighborhood to each restaurant

In [2]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import contextily as cx

nyc = gpd.read_file("./data/nyc.geojson")
nyc_restaurant = pd.read_csv("./data/google_maps_restaurants(cleaned).csv")

In [4]:
# convert nyc_restaurant to geopandas dataframe, specify CRS the same as nyc.crs
nyc_restaurant_gdf = gpd.GeoDataFrame(
    nyc_restaurant, geometry=gpd.points_from_xy(nyc_restaurant.Lon, nyc_restaurant.Lat), crs=nyc.crs)

In [6]:
# inspect crs

nyc_restaurant_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [11]:
# use sjoin to identify which neighborhood (Community District) each restaurant is in

joined_gdf = nyc_restaurant_gdf.sjoin(nyc, how='inner', predicate='intersects')

joined_gdf[['Name','Rating','Rating Count','Price Category',"Address",'BoroName','NTAName','CDTANAME']].head()

,Name,Rating,Rating Count,Price Category,Address,BoroName,NTAName,CDTANAME
2,Joe's Restaurant,4.6,812.0,2.0,"6611 Forest Ave, Ridgewood, NY 11385",Queens,Ridgewood,QN05 Ridgewood-Maspeth-Middle Village (CD 5 Ap...
6,Mexican Cantina Restaurant & Bar,4.5,257.0,2.0,"1736 Victory Blvd, Staten Island, NY 10314",Staten Island,Westerleigh-Castleton Corners,SI01 North Shore (CD 1 Equivalent)
8,Golden Krust Caribbean Restaurant,3.7,82.0,1.0,"1014a Nostrand Ave, Brooklyn, NY 11225",Brooklyn,Prospect Lefferts Gardens-Wingate,BK09 Crown Heights (South) (CD 9 Approximation)
12,POLONICA RESTAURANT,4.5,227.0,2.0,"8303 3rd Ave, Brooklyn, NY 11209",Brooklyn,Bay Ridge,BK10 Bay Ridge-Dyker Heights (CD 10 Approximat...
13,Serafina Italian Restaurant Tribeca,4.3,1057.0,2.0,"95 W Broadway, New York, NY 10007",Manhattan,Tribeca-Civic Center,MN01 Financial District-Tribeca (CD 1 Equivalent)

In [19]:
# Which community has the most expensive

joined_gdf.groupby("CDTANAME", as_index=False).agg(
    Boro=("BoroName", "first"),
    NTAName=("NTAName", "first"),
    count=('Rating', 'count'),
    avg_rating=('Rating', 'mean'),
    avg_price_category=('Price Category', 'mean'),
)

,CDTANAME,Boro,NTAName,count,avg_rating,avg_price_category
0,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),Brooklyn,Greenpoint,10,4.260000,1.750000
1,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,Brooklyn,Brooklyn Heights,17,4.300000,1.941176
2,BK03 Bedford-Stuyvesant (CD 3 Approximation),Brooklyn,Bedford-Stuyvesant (East),2,4.350000,1.000000
3,BK04 Bushwick (CD 4 Equivalent),Brooklyn,Bushwick (West),8,4.237500,1.571429
4,BK05 East New York-Cypress Hills (CD 5 Approxi...,Brooklyn,Cypress Hills,10,3.860000,1.333333
5,BK06 Park Slope-Carroll Gardens (CD 6 Approxim...,Brooklyn,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,10,4.430000,1.555556
6,BK07 Sunset Park-Windsor Terrace (CD 7 Approxi...,Brooklyn,Sunset Park (West),12,4.075000,1.500000
7,BK08 Crown Heights (North) (CD 8 Approximation),Brooklyn,Crown Heights (North),5,4.140000,1.750000
8,BK09 Crown Heights (South) (CD 9 Approximation),Brooklyn,Prospect Lefferts Gardens-Wingate,8,4.100000,1.285714
9,BK10 Bay Ridge-Dyker Heights (CD 10 Approximat...,Brooklyn,Bay Ridge,18,4.477778,1.764706
10,BK11 Bensonhurst-Bath Beach (CD 11 Approximation),Brooklyn,Bensonhurst,5,4.420000,2.000000
11,BK12 Borough Park-Kensington (CD 12 Approximat...,Brooklyn,Borough Park,9,3.933333,1.250000
12,BK14 Flatbush-Midwood (CD 14 Approximation),Brooklyn,Flatbush,8,4.125000,1.571429
13,BK15 Sheepshead Bay-Gravesend (East) (CD 15 Ap...,Brooklyn,Gravesend (East)-Homecrest,3,4.300000,2.000000
14,BK16 Ocean Hill-Brownsville (CD 16 Approximation),Brooklyn,Brownsville,1,3.300000,1.000000
15,BK17 East Flatbush (CD 17 Approximation),Brooklyn,East Flatbush-Farragut,8,4.100000,1.333333
16,BK18 Canarsie-Flatlands (CD 18 Approximation),Brooklyn,Flatlands,10,4.130000,1.500000
17,BX04 Highbridge-Concourse (CD 4 Approximation),Bronx,Highbridge,1,4.200000,2.000000
18,BX05 Morris Heights-Mount Hope (CD 5 Approxima...,Bronx,Fordham Heights,2,4.150000,1.500000
19,BX06 Tremont-Belmont-West Farms (CD 6 Approxim...,Bronx,Tremont,1,4.400000,1.000000
20,BX11 Pelham Parkway-Morris Park (CD 11 Approxi...,Bronx,Morris Park,3,4.000000,1.666667
21,MN01 Financial District-Tribeca (CD 1 Equivalent),Manhattan,Tribeca-Civic Center,18,4.366667,2.187500
22,MN02 Greenwich Village-SoHo (CD 2 Equivalent),Manhattan,West Village,15,4.373333,2.133333
23,MN03 Lower East Side-Chinatown (CD 3 Equivalent),Manhattan,East Village,11,4.290909,1.800000
24,MN04 Chelsea-Hell's Kitchen (CD 4 Approximation),Manhattan,Chelsea-Hudson Yards,10,4.280000,2.000000
25,MN05 Midtown-Flatiron-Union Square (CD 5 Appro...,Manhattan,Midtown-Times Square,14,4.292857,2.461538
26,MN06 East Midtown-Murray Hill (CD 6 Approximat...,Manhattan,Gramercy,4,4.600000,2.250000
27,MN07 Upper West Side (CD 7 Approximation),Manhattan,Upper West Side (Central),1,4.400000,2.000000
28,MN08 Upper East Side-Roosevelt Island (CD 8 Eq...,Manhattan,Upper East Side-Yorkville,2,3.850000,2.000000
29,MN09 Morningside Heights-Hamilton Heights (CD ...,Manhattan,Manhattanville-West Harlem,2,4.350000,1.500000
30,MN10 Harlem (CD 10 Equivalent),Manhattan,Harlem (South),2,3.850000,1.000000
31,MN11 East Harlem (CD 11 Equivalent),Manhattan,East Harlem (North),2,4.200000,1.000000
32,MN12 Washington Heights-Inwood (CD 12 Equivalent),Manhattan,Washington Heights (South),4,3.875000,1.000000
33,QN01 Astoria-Queensbridge (CD 1 Equivalent),Queens,Astoria (North)-Ditmars-Steinway,1,4.500000,2.000000
34,QN02 Long Island City-Sunnyside-Woodside (CD 2...,Queens,Sunnyside,1,4.600000,2.000000
35,QN03 Jackson Heights-East Elmhurst (CD 3 Appro...,Queens,Jackson Heights,3,4.366667,1.333333
36,QN04 Elmhurst-Corona (CD 4 Approximation),Queens,Elmhurst,4,4.275000,1.750000
37,QN05 Ridgewood-Maspeth-Middle Village (CD 5 Ap...,Queens,Ridgewood,6,4.400000,1.666667
38,QN06 Forest Hills-Rego Park (CD 6 Approximation),Queens,Rego Park,1,4.700000,2.000000
39,QN10 South Ozone Park-Howard Beach (CD 10 Appr...,Queens,Ozone Park,1,4.100000,1.000000
40,QN12 Jamaica-St. Albans-Hollis (CD 12 Approxim...,Queens,Baisley Park,1,4.500000,2.000000
41,SI01 North Shore (CD 1 Equivalent),Staten Island,Westerleigh-Castleton Corners,34,4.244118,1.653846
42,SI02 Mid-Island (CD 2 Approximation),Staten Island,New Springville-Willowbrook-Bulls Head-Travis,1,4.200000,2.000000